esphome:
  name: Tecalor_HP
  friendly_name: HeatPump_CAN
  platformio_options:
    build_flags:
      - "-std=gnu++2a"
    build_unflags:
      - "-std=gnu++11"
      - "-fno-rtti"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:
  level: INFO
  baud_rate: 0
  hardware_uart: UART1

# Enable Home Assistant API
api:
  encryption:
    key: "1cSivcBYHZBouiCgueZtgbwR0cBoKPVc48JNhvXK6JI="

ota:
  platform: esphome

time:
  - platform: homeassistant
    id: homeassistant_time

substitutions:
  interval_very_fast: 15s
  interval_fast: 30s
  interval_medium: 60s
  interval_slow: 5min
  interval_very_slow: 15min
  interval_once_in_a_while: 1h

  entity_room_temperature: "sensor.avg_temp"
  entity_humidity: "input_number.avg_luftfeuchtigkeit"

#########################################
#                                       #
#   SPI configuration                   #
#                                       #
#########################################
spi:
  id: McpSpi
  clk_pin: GPIO39
  mosi_pin: GPIO40
  miso_pin: GPIO41

#########################################
#                                       #
#   CAN configuration                   #
#                                       #
#########################################
canbus:
  - id: !extend wp_can
    platform: mcp2515
    spi_id: McpSpi
    cs_pin: GPIO42
    bit_rate: 20kbps

#########################################
#                                       #
#   Buttons                             #
#                                       #
#########################################
button:
  - platform: restart
    name: "Restart Tecalor_COM"

#########################################
#                                       #
#   Ethernet Konfiguration              #
#                                       #
#########################################

wifi:
  # Set up a wifi access point
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "Tecalor Fallback Hotspot"
    password: "SmartHome"

#########################################
#                                       #
#   Packages                            #
#                                       #
#########################################
packages:
# energymeter: !include OneESP32ToRuleThemAll/yaml/energymeter.yaml
# evu: !include OneESP32ToRuleThemAll/yaml/evu.yaml
# watermeter: !include OneESP32ToRuleThemAll/yaml/watermeter.yaml
# sensors: !include OneESP32ToRuleThemAll/yaml/sensors.yaml
# thz404: !include OneESP32ToRuleThemAll/yaml/thz404.yaml
#  thz504: !include OneESP32ToRuleThemAll/yaml/thz504.yaml
 thz55eco: !include github://PhagoZ/Tecalor/OneESP32ToRuleThemAll/yaml/thz5_5_eco.yaml
# ttf07: !include OneESP32ToRuleThemAll/yaml/ttf07.yaml
# wpl13: !include OneESP32ToRuleThemAll/yaml/wpl13.yaml
# kondensatpumpe: !include OneESP32ToRuleThemAll/yaml/kondensatpumpe.yaml
# sgready: !include OneESP32ToRuleThemAll/yaml/sg_ready.yaml
